export const USER_GET_FREIND_REQUESTS_BEGIN = 'USER_GET_FREIND_REQUESTS_BEGIN';
export const USER_GET_FREIND_REQUESTS_SUCCESS = 'USER_GET_FREIND_REQUESTS_SUCCESS';
export const USER_GET_FREIND_REQUESTS_FAILURE = 'USER_GET_FREIND_REQUESTS_FAILURE';
export const USER_GET_FREIND_REQUESTS_DISMISS_ERROR = 'USER_GET_FREIND_REQUESTS_DISMISS_ERROR';
