export const MEDIA_MAKE_MOVIE_COMMENT_BEGIN = 'MEDIA_MAKE_MOVIE_COMMENT_BEGIN';
export const MEDIA_MAKE_MOVIE_COMMENT_SUCCESS = 'MEDIA_MAKE_MOVIE_COMMENT_SUCCESS';
export const MEDIA_MAKE_MOVIE_COMMENT_FAILURE = 'MEDIA_MAKE_MOVIE_COMMENT_FAILURE';
export const MEDIA_MAKE_MOVIE_COMMENT_DISMISS_ERROR = 'MEDIA_MAKE_MOVIE_COMMENT_DISMISS_ERROR';
export const MEDIA_MAKE_TV_COMMENT_BEGIN = 'MEDIA_MAKE_TV_COMMENT_BEGIN';
export const MEDIA_MAKE_TV_COMMENT_SUCCESS = 'MEDIA_MAKE_TV_COMMENT_SUCCESS';
export const MEDIA_MAKE_TV_COMMENT_FAILURE = 'MEDIA_MAKE_TV_COMMENT_FAILURE';
export const MEDIA_MAKE_TV_COMMENT_DISMISS_ERROR = 'MEDIA_MAKE_TV_COMMENT_DISMISS_ERROR';
