export const COMMON_ACTORS_BEGIN = 'COMMON_ACTORS_BEGIN';
export const COMMON_ACTORS_SUCCESS = 'COMMON_ACTORS_SUCCESS';
export const COMMON_ACTORS_FAILURE = 'COMMON_ACTORS_FAILURE';
export const COMMON_ACTORS_DISMISS_ERROR = 'COMMON_ACTORS_DISMISS_ERROR';
export const COMMON_MOVIES_BEGIN = 'COMMON_MOVIES_BEGIN';
export const COMMON_MOVIES_SUCCESS = 'COMMON_MOVIES_SUCCESS';
export const COMMON_MOVIES_FAILURE = 'COMMON_MOVIES_FAILURE';
export const COMMON_MOVIES_DISMISS_ERROR = 'COMMON_MOVIES_DISMISS_ERROR';
