export const PROFILE_GET_WALL_BEGIN = 'PROFILE_GET_WALL_BEGIN';
export const PROFILE_GET_WALL_SUCCESS = 'PROFILE_GET_WALL_SUCCESS';
export const PROFILE_GET_WALL_FAILURE = 'PROFILE_GET_WALL_FAILURE';
export const PROFILE_GET_WALL_DISMISS_ERROR = 'PROFILE_GET_WALL_DISMISS_ERROR';
export const PROFILE_GET_TIMELINE_BEGIN = 'PROFILE_GET_TIMELINE_BEGIN';
export const PROFILE_GET_TIMELINE_SUCCESS = 'PROFILE_GET_TIMELINE_SUCCESS';
export const PROFILE_GET_TIMELINE_FAILURE = 'PROFILE_GET_TIMELINE_FAILURE';
export const PROFILE_GET_TIMELINE_DISMISS_ERROR = 'PROFILE_GET_TIMELINE_DISMISS_ERROR';
